name: CI
on:
  push:
    branches:
    - 'master'
    - 'release-**'
  pull_request:
jobs:
  ci:
    name: Lint and unit test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"
    - name: Environment
      run: |
        go version
        go env
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Code coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
